server:
  port: 8022
spring:
  application:
    name: rabbitmq-consumer
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

    #确认消息已发送到交换机(Exchange)
    publisher-returns: true